"""Utility to convert STIL files to simple GASC format.

This script demonstrates how to use the ``STILParser`` from the project to
parse a STIL file and extract a very small subset of the information.  The
result is written to a ``.gasc`` file with a structure similar to the one
requested in the user instructions.

The script is intentionally lightweight and only relies on the parse tree
structure generated by ``STILParser``.  It walks the tree and collects:

* The signal names declared in the ``Signals`` block.
* The vector data contained in pattern statements.
* Micro-instructions (``Call``, ``Loop``, ``Stop`` …) that immediately
  precede a vector.
* The active waveform table (``W`` statement).

The produced ``.gasc`` file contains a header with the list of signals and a
``SPM_PATTERN (SCAN)`` block with one line per vector.  Each line contains the
vector data, the micro-instruction and the waveform table name, when
available.

Note
----
The repository does not ship the ``lark`` dependency that powers the parser.
Running this script requires installing ``lark`` into the environment.

OPTIMIZED VERSION with streaming output and real-time progress display.
"""

from __future__ import annotations

from ast import Pass
import os
from queue import Empty
import sys
from dataclasses import dataclass
from typing import List

from lark import Lark, Tree, Token, LarkError
from STILToGascStream import STILToGascStream

try:  # Try importing the package as an installed dependency first
    from Semi_ATE.STIL.parsers.STILParser import STILParser
except ImportError:  # pragma: no cover - fallback for local execution
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    sys.path.insert(0, repo_root)
    from Semi_ATE.STIL.parsers.STILParser import STILParser

from lark import Tree, Token


class STILToGascStreamATE(STILToGascStream):
    """Convert STIL files to a simple GASC-like format - STREAMING OPTIMIZED VERSION."""
    def __init__(self, stil_file, target_file, progress_callback=None, debug=False):
        STILToGascStream.__init__(self, stil_file, target_file, progress_callback, debug)
        self.target_file = target_file
        self.progress_callback = progress_callback
        self.debug = debug
    
    # override write_pattern_line_streaming
    def write_pattern_line_streaming(self, vec: str, instr: str, wft: str, label_value: str) -> None:
        """流式写入模式行数据到输出文件"""
        if not self.pattern_section_started:
            self.output_file.write("SPM_PATTERN (SCAN) {\n")
            self.pattern_section_started = True

        self.output_file.write(f"       *{vec}*{instr};")
        if wft:
            self.output_file.write(f"{wft};")
        if label_value: # strip ':' and '"'
            self.output_file.write(f"{label_value.strip(":").strip("\"")};")
        self.output_file.write("\n")
        
        # Update progress counter
        self.vector_count += 1
        # 优化进度更新频率：前10000个每1000更新，之后每5000更新
        update_interval = 1000 if self.vector_count <= 10000 else 5000
        if self.progress_callback and self.vector_count % update_interval == 0:
            progress = self.read_size / self.file_size * 100
            self.progress_callback(f"已处理 {self.vector_count:,} 个向量，进度:{progress:.1f}%...")

    def convert(self):
        pass

       

    